### ISSUE TITLE
大佬能教一下怎么使用这个吗...  新手不知道该怎么使用

### ISSUE THREAD

**Issue by SeaGull1919** [KagurazakaNyaa/mcsm-docker#1]

**Comment by KagurazakaNyaa** [comment]
我是这样写了一个docker-compose.yml
```yaml
version: '3'

services:
  web:
    image: kagurazakanyaa/mcsm:web
    restart: always
    ports:
      - "23333:23333"
    volumes:
      - ./web/data:/opt/mcsmanager/web/data
      - ./web/logs:/opt/mcsmanager/web/logs

  daemon:
    image: kagurazakanyaa/mcsm:daemon
    restart: always
    ports:
      - "24444:24444"
    volumes:
      - ./daemon/data:/opt/mcsmanager/daemon/data
      - ./daemon/logs:/opt/mcsmanager/daemon/logs
      - /var/run/docker.sock:/var/run/docker.sock
```
然后就正常使用就行
